ROADMAP = {
    "Python": "Learn Python Basics",
    "SQL": "Learn SQL and Database Queries",
    "Excel": "Master Excel for Data Analysis",
    "Pandas": "Learn Pandas Library",
    "NumPy": "Learn NumPy Fundamentals",
    "Apache Spark": "Learn Apache Spark",
    "Hadoop": "Understand Hadoop Ecosystem",
    "Airflow": "Learn Apache Airflow",
    "Flask": "Build Flask Web Applications",
    "Git": "Learn Git & GitHub",
    "Machine Learning": "Study Machine Learning",
    "Deep Learning": "Learn Deep Learning",
    "TensorFlow": "Practice TensorFlow",
    "Java": "Learn Java Programming",
    "Spring Boot": "Build REST APIs using Spring Boot",
    "React": "Learn React.js",
    "Node.js": "Learn Node.js",
    "Express.js": "Build APIs using Express.js",
    "MongoDB": "Learn MongoDB Database",
    "HTML": "Master HTML",
    "CSS": "Master CSS",
    "JavaScript": "Learn JavaScript",
    "Bootstrap": "Learn Bootstrap",
    "REST API": "Understand REST APIs",
    "OOP": "Master Object-Oriented Programming",
    "Linux": "Learn Linux Basics"
}